# Generated by Django 5.0.3 on 2024-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('in_highlight', 'In Highlight'), ('published', 'Published')], default='published', max_length=30),
        ),
    ]
