# Generated by Django 5.0.3 on 2024-04-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfaq',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Perguntas Frequentes de Productos'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
