# Generated by Django 5.0.3 on 2024-05-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specification',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
