# Generated by Django 5.0.3 on 2024-04-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_sale_alter_partner_options_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=50),
        ),
    ]
