# Generated by Django 5.0.3 on 2024-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_color_is_published_gender_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrocel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='website/galeria/')),
                ('title', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='ecommerce.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
