# Generated by Django 5.0.3 on 2024-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_order_customer_alter_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='description',
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='value_hexadecimal',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
