# Generated by Django 5.0.3 on 2024-04-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_color_description_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.sale'),
        ),
    ]
