# Generated by Django 5.0.3 on 2024-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_supporter_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrocel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
