# Generated by Django 5.0.3 on 2024-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.size'),
        ),
    ]
