# Generated by Django 5.0.3 on 2024-04-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_carrocel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrocel',
            name='category',
        ),
        migrations.AddField(
            model_name='carrocel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productcategory'),
            preserve_default=False,
        ),
    ]
