# Generated by Django 5.0.3 on 2024-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_color_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='ecommerce.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(blank=True, to='ecommerce.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='ecommerce.size'),
        ),
    ]
